subjects: [ англичанин, аргентинец, балиец, болгарин, голландец, датчанин, египтянин, испанец, китаец, кореец, мексиканец, норвежец, новозеландец, португалец, француз, швед, японец ]
objectToSubjectPrefix: "Тот, кто"
objectsInfos:
  - objects: [ Camel, Dunhill, Kool, Chesterfield, Old Gold, Lucky Strike, Marlboro, Newport,Pall Mall, Parliament, Rothmans, Salem, Tiparillo, Winfield, Winston ]
    verb: курит
    intro: "Каждый курит ровно одну марку сигарет. Это могут быть: "

  - objects: [ бурбон, виски, вино, грог, какао, кофе, коньяк, пиво, пунш, саке, сок, чай ]
    verb: пьёт
    intro: "Каждый пьёт ровно один напиток. Это могут быть: "

  - objects: [ бадминтон, волейбол, гольф, крикет, регби, теннис, футбол, хоккей ]
    verb: играет в
    intro: "Каждый играет ровно в один вид спорта. Это могут быть: "


#subjects: [ Маша, Даша, Катя, Света, Ира, Валентина, Наташа, Полина, Оля, Аня, Лиза ]
#objectToSubjectPrefix: "Та, кто"
#objectsInfos:
#  -
#    objects: [ китайский, японский, английский, французский, норвежский, немецкий, испанский ]
#    verb: учит
#    intro: "Каждая учит ровно один язык. Это могут быть: "
#  -
#    objects: [ бегом, плаванием, танцами, хайкингом, теннисом, бадминтоном, волейболом ]
#    verb: занимается
#    intro: "Каждая занимается ровно одним видом спорта из списка: "
#  -
#    objects: [ балетом, пением, живописью, литературой, музыкой, скульптурой, кино ]
#    verb: увлекается
#    intro: "Каждая увлекается ровно одним видом искусств из следующих: "
